;; This file bootstraps the configuration, which is divided into
;; a number of other files.
;; the file named subdirs.el in the direcotor load-path
;; is a important file that let emacs auto-load the director
;; and sub-director's file of the load-pat
(add-to-list 'load-path "F:/Emacs/site-lisp/")
(add-to-list 'load-path "F:/Emaca/site-lisp/elib/")
;;----------------------------------------------------------------------------
;; Require librarys for specific features and modes
;;----------------------------------------------------------------------------
;;(require 'wget)
(require 'color-theme)
(require 'color-theme-solarized)
(require 'color-theme-molokai)
(require 'smex)
(require 'cygwin-mount)
(require 'session)
(require 'powerline)
(require 'js2-mode)
(require 'cl)
;;(require 'cedet)
(require 'html-helper-mode)
(require 'remember)
;;(require 'unicad)
;;(require 'jde)
;;----------------------------------------------------------------------------
;; Load configuration for specific feature and modes
;; tips : powerline should aloways load ahead theme 
;;----------------------------------------------------------------------------
(load "init-powerline.el")
(load "init-smex.el")
(load "init-cedet.el")
(load "init-org.el")
(load "init-html.el")
(load "init-javascript.el")
(load "init-theme.el")
(load "init-session.el")
(load "init-util.el")
(load "init-macro.el")
(load "init-html-helper.el")
;;----------------------------------------------------------------------------
;; Config system show and view or some feature and mode
;;----------------------------------------------------------------------------
;; do not back up file
(setq-default make-backup-files nil)
;; replace tab with same count space when type tab
;; Make sure spaces are used when indenting code
(setq-default indent-tabs-mode nil)
;; close auto run message
(setq inhibit-startup-message t)
;; close tool bar
(tool-bar-mode nil)
;;(menu-bar-mode nil)
;; close scroll bar
(scroll-bar-mode nil)
;; open mysql console callback
(setq sql-mysql-options '("-C" "-t" "-f" "-n"))
;; set encoding system
(prefer-coding-system 'utf-8)
(setq current-language-environment "UTF-8")
;; set mouse event for up or down font size
(global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
(global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
;; set how much lines and columns the emacs-frame default show
(setq default-frame-alist '( (width . 100) (height . 30)))
;;----------------------------------------------------------------------------
;; Configuration Windows Font this is very important for 
;; windows user beacause a nice font will take a nice day
;;----------------------------------------------------------------------------
;; Setting English Font
(set-face-attribute 'default nil :font "Consolas 12")   
;; Chinese Font 
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font (frame-parameter nil 'font)
                    charset
                    (font-spec :family "Microsoft Yahei" :size 12)))
;;----------------------------------------------------------------------------
;; This config is auto-generated by emacs option menu-bar configuer function
;;----------------------------------------------------------------------------
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(current-language-environment "UTF-8")
 '(menu-bar-mode nil)
 '(scroll-bar-mode nil)
 '(tool-bar-mode nil)
 '(truncate-lines nil))
;;----------------------------------------------------------------------------
;; Define author and email information
;;----------------------------------------------------------------------------
(setq user-mail-address "502359010@qq.com")
(setq user-full-name "fengjiantao")
;; author: fengjiantao
;; email: 502359010@qq.com
;; End:
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(mode-line ((t (:foreground "#ffffff" :background "#000000" :box nil))))
 '(mode-line-inactive ((t (:foreground "#f9f9f9" :background "#666666" :box nil)))))
